kind: pipeline
name: default

steps:
  - name: restore
    image: plugins/s3-cache
    settings:
      pull: true
      restore: true

  - name: test
    image: ruby
    commands:
      - bundle update --bundler
      - bundle install --path vendor/bundle
      - bundle exec rspec

  - name: rebuild
      image: plugins/s3-cache
      settings:
        pull: true
        rebuild: true
        mount:
          - vendor/bundle


  - name: textlint
    image: node
    commands:
      - npm install textlint
      - npm install textlint-rule-preset-ja-technical-writing
      - $(npm bin)/textlint --format pretty-error --preset ja-technical-writing README.md
